#!/usr/bin/env bash
#
# Clean up backups

if [ -z "$1" ]; then
  echo 'USAGE: bk-clean BACKUP'
  exit
fi

pushd "$HOME/.wag" > /dev/null || exit
if [ "$1" == 'all' ]; then
  rm -v -- *.tar
else
  rm "$1"
fi
popd > /dev/null || exit
